# Generated by Django 3.1 on 2020-08-27 14:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Calculator',
            fields=[
                ('id', models.CharField(default=True, max_length=100, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('num1', models.CharField(max_length=100)),
                ('num2', models.CharField(max_length=100)),
                ('operation', models.CharField(max_length=2)),
                ('result', models.CharField(max_length=100)),
                ('date', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
            ],
        ),
    ]
