# Generated by Django 3.1 on 2020-08-27 15:16

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0003_auto_20200827_1514'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calculator',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 27, 15, 16, 8, 992524, tzinfo=utc), editable=False),
        ),
    ]
