# Generated by Django 3.1 on 2020-08-27 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0005_auto_20200827_1545'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calculator',
            name='date',
        ),
    ]
